### ISSUE TITLE
iが未初期化

### ISSUE THREAD

**Issue by hikalium** [Knium/knicc#1]
https://github.com/Knium/knicc/blob/14ac8833d7d9543e0e87a1cecc4adff8f825c23f/main.c#L127
ローカル変数iが初期化されていません。`i = 0;` としましょう。
コンパイル時に `-Wall`オプションをつけて、警告を全部出すようにするとこういった類のミスを減らせます。

**Comment by Krout0n** [comment]
なるほど，めっちゃ初歩的なミスでした・・・ ありがとうございます！ 🙏
